# Most Wanted Powerups by @gaycoderprincess
# enjoy, nya~ :3

style_mk64 = true		# set to false for Re-Volt style, true for Mario Kart style
show_overhead = true		# display other cars' powerups above them